### ISSUE TITLE
IPA command throughs Ruby exceptions

### ISSUE THREAD

**Issue by Forsarion** [nomad/shenzhen#276]
Hi everybody!

I receive following output when trying to use _ipa_ command:

```
Mac-mini-Dmitriy:Product bamboo-server$ sudo gem install shenzhen
Fetching: shenzhen-0.14.2.gem (100%)
Successfully installed shenzhen-0.14.2
Parsing documentation for shenzhen-0.14.2
Installing ri documentation for shenzhen-0.14.2
1 gem installed
Mac-mini-Dmitriy:Product bamboo-server$ ipa
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'highline' (~> 1.6.11) - did find: [highline-1.7.2] (Gem::LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1209:in `block in activate_dependencies'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1212:in `block in activate_dependencies'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
    from /usr/bin/ipa:22:in `<main>'
Mac-mini-Dmitriy:Product bamboo-server$ 
```

I have both version of highline installed:

```
Mac-mini-Dmitriy:Product bamboo-server$ gem list highline

*** LOCAL GEMS ***

highline (1.7.2, 1.6.11)

```

Have anybody faced this issue?

Thanks for help in advance.

**Comment by KrauseFx** [comment]
You could try fixing it by uninstalling the `highline` version 1.7.2, not sure if that helps.

**Comment by AndreyMoskvin** [comment]
I've tried uninstalling - than *ipa* throws another exception.

**Comment by micky2be** [comment]
Having same problem. One need 1.6.11 and the other 1.7.2

**Comment by micky2be** [comment]
As mentioned on #257, updating commander fixes it
