### ISSUE TITLE
Unable to upload IPA using shenzhen on Travis CI

### ISSUE THREAD

**Issue by a1cooke** [nomad/shenzhen#288]
Hi,

I have exhausted everything I found on the internet in an attempt to solve this problem.

I am getting the following stack trace when I attempt to upload an IPA to HockeyApp.

```
[14:49:38]: fastlane finished with errors
/Users/travis/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/net/http.rb:921:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
    from /Users/travis/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
    from /Users/travis/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
    from /Users/travis/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/net/http.rb:921:in `connect'
    from /Users/travis/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
    from /Users/travis/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/net/http.rb:851:in `start'
    from /Users/travis/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/net/http.rb:1373:in `request'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response/follow_redirects.rb:79:in `perform_with_redirection'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response/follow_redirects.rb:65:in `call'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/faraday-0.9.1/lib/faraday/request/multipart.rb:14:in `call'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/krausefx-shenzhen-0.14.5/lib/shenzhen/plugins/hockeyapp.rb:29:in `upload_build'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/lib/fastlane/actions/hockey.rb:43:in `run'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/lib/fastlane/runner.rb:128:in `block in execute_action'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/lib/fastlane/runner.rb:127:in `chdir'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/lib/fastlane/runner.rb:127:in `execute_action'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/lib/fastlane/fast_file.rb:120:in `method_missing'
    from (eval):49:in `block (3 levels) in parse'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/lib/fastlane/lane.rb:29:in `call'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/lib/fastlane/lane.rb:29:in `call'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/lib/fastlane/runner.rb:50:in `block in execute'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/lib/fastlane/runner.rb:44:in `chdir'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/lib/fastlane/runner.rb:44:in `execute'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/lib/fastlane/command_line_handler.rb:31:in `handle'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/bin/fastlane:35:in `block (2 levels) in run'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/bin/fastlane:124:in `run'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/fastlane-1.13.0/bin/fastlane:130:in `<top (required)>'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/fastlane:23:in `load'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/fastlane:23:in `<main>'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
    from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
```

I've tried:
- `rvm osx-ssl-certs update all`
- Switching versions of Ruby
- Using Homebrew to upgrade OpenSSL but all to no joy

Findings:
I did try and use a ruby script from SSL-tools: https://github.com/mislav/ssl-tools and ran the doctor.rb on travis with the following output:

```
OpenSSL 1.0.1j 15 Oct 2014: /etc/openssl
SSL_CERT_DIR=""
SSL_CERT_FILE="/usr/local/etc/openssl/cert.pem"
HEAD https://upload.hockeyapp.net:443
OK
```

I've tried the solutions proposed here:
- https://github.com/KrauseFx/fastlane/issues/258
- https://github.com/nomad/shenzhen/issues/255

Environment Details:
- Ruby Version: ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-darwin14.1.0]
- RVM Version: rvm 1.26.11 (latest) by Wayne E. Seguin wayneeseguin@gmail.com, Michal Papis mpapis@gmail.com [https://rvm.io/]

I've concluded at some point along the way that the issue is somewhat isolated to Faraday but my limited knowledge of it has stopped me from tracking down the issue further.

**Comment by chillpop** [comment]
@a1cooke are you using `osx_image: xcode6.4` on Travis?  If so I think that's the source of the problem: that OS X image is not set up the same way as earlier images.  I'm having the same issue and don't think it's related to shenzhen but something else in the environment.

**Comment by a1cooke** [comment]
@chillpop Yeah we are using xcode6.4, any ideas on what is different did you get it working with xcode6.3? I'll be honest I haven't revisited it.  I just switched to using a script to upload build directly to hockey app, I will hopefully get some time next week to explore more.

**Comment by chillpop** [comment]
I'm still investigating a fix.  It appears to be a problem on `beta-xcode6.3`, but `beta-xcode6.2` and the default (which uses Xcode 6.1) _appear_ to work based on testing with doctor.rb from ssl-tools.

**Comment by chillpop** [comment]
Adding the following commands to `before_install` appears to fix the problem:
```yml
  - sudo security delete-certificate -Z 2F173F7DE99667AFA57AF80AA2D1B12FAC830338 /System/Library/Keychains/SystemRootCertificates.keychain
  - rvm osx-ssl-certs update all
```

I believe the issue is that the expired GlobalSign root certificate is in the keychain of those Travis OS X images. The first line deletes the expired certificate. The second line re-exports the revised certificates from the keychain (propagating the delete to openssl).

(https://support.globalsign.com/customer/portal/articles/1426272-expiration-of-old-globalsign-2014-root-ca-certificate)

This issue should be closed since it is an issue with Travis, not shenzhen.
